;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        amx
        beginning-of-visual-line
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-indent-line-or-region
        counsel-yank-pop
        electric-pair-delete-pair
        end-of-visual-line
        gcm-scroll-up
        hydra--digit-argument
        hydra-multiple-cursors/nil
        indent-for-tab-command
        kill-region
        kill-visual-line
        markdown-outdent-or-delete
        nxml-electric-slash
        org-delete-char
        org-edit-src-save
        org-self-insert-command
        paredit-backward-kill-word
        paredit-delete-char
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        save-all-buffers-no-confirm
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-git-grep
        counsel-mark-ring
        gcm-scroll-down
        handle-switch-frame
        hydra-multiple-cursors/mc/cycle-backward
        hydra-multiple-cursors/mc/cycle-forward
        hydra-multiple-cursors/mc/mark-all-like-this
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-all-symbols-like-this
        hydra-multiple-cursors/mc/mark-all-symbols-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-next-like-this-symbol
        hydra-multiple-cursors/mc/mark-next-symbol-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this-symbol
        hydra-multiple-cursors/mc/mark-previous-symbol-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/mc/unmark-previous-like-this
        other-frame
        switch-to-last-buffer
        ))
