;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        amx
        beginning-of-visual-line
        counsel-yank-pop
        end-of-visual-line
        hydra-multiple-cursors/nil
        indent-for-tab-command
        kill-region
        org-edit-src-save
        org-self-insert-command
        paredit-backward-kill-word
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-mark-ring
        hydra-multiple-cursors/mc/cycle-backward
        hydra-multiple-cursors/mc/cycle-forward
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-next-symbol-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/mark-previous-symbol-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/mc/unmark-previous-like-this
        ))
